Avoid throwing non exception
HttpResponseBadRequest is not an exception, so it should not be thrown.
Otherwise it fails with:

File "serveradmin/serveradmin/resources/views.py", line 40, in index
  raise HttpResponseBadRequest('No matching current collection')
TypeError: exceptions must derive from BaseException