Fix AttributeError: 'int' object has no attribute 'as_tuple'
The get_value method of ServerNumberAttribute that might get called
expects the passed value to be a decimal and can't handle integers.